/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsDropdownsRouteImport } from './routes/settings/dropdowns'
import { Route as SettingsDodgeMappingsRouteImport } from './routes/settings/dodge-mappings'
import { Route as ProjectIdRouteImport } from './routes/project/$id'
import { Route as ProjectChangelogIdRouteImport } from './routes/project-changelog.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDropdownsRoute = SettingsDropdownsRouteImport.update({
  id: '/settings/dropdowns',
  path: '/settings/dropdowns',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDodgeMappingsRoute = SettingsDodgeMappingsRouteImport.update({
  id: '/settings/dodge-mappings',
  path: '/settings/dodge-mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectChangelogIdRoute = ProjectChangelogIdRouteImport.update({
  id: '/project-changelog/$id',
  path: '/project-changelog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project-changelog/$id': typeof ProjectChangelogIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/settings/dodge-mappings': typeof SettingsDodgeMappingsRoute
  '/settings/dropdowns': typeof SettingsDropdownsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project-changelog/$id': typeof ProjectChangelogIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/settings/dodge-mappings': typeof SettingsDodgeMappingsRoute
  '/settings/dropdowns': typeof SettingsDropdownsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project-changelog/$id': typeof ProjectChangelogIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/settings/dodge-mappings': typeof SettingsDodgeMappingsRoute
  '/settings/dropdowns': typeof SettingsDropdownsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project-changelog/$id'
    | '/project/$id'
    | '/settings/dodge-mappings'
    | '/settings/dropdowns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project-changelog/$id'
    | '/project/$id'
    | '/settings/dodge-mappings'
    | '/settings/dropdowns'
  id:
    | '__root__'
    | '/'
    | '/project-changelog/$id'
    | '/project/$id'
    | '/settings/dodge-mappings'
    | '/settings/dropdowns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectChangelogIdRoute: typeof ProjectChangelogIdRoute
  ProjectIdRoute: typeof ProjectIdRoute
  SettingsDodgeMappingsRoute: typeof SettingsDodgeMappingsRoute
  SettingsDropdownsRoute: typeof SettingsDropdownsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dropdowns': {
      id: '/settings/dropdowns'
      path: '/settings/dropdowns'
      fullPath: '/settings/dropdowns'
      preLoaderRoute: typeof SettingsDropdownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dodge-mappings': {
      id: '/settings/dodge-mappings'
      path: '/settings/dodge-mappings'
      fullPath: '/settings/dodge-mappings'
      preLoaderRoute: typeof SettingsDodgeMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-changelog/$id': {
      id: '/project-changelog/$id'
      path: '/project-changelog/$id'
      fullPath: '/project-changelog/$id'
      preLoaderRoute: typeof ProjectChangelogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectChangelogIdRoute: ProjectChangelogIdRoute,
  ProjectIdRoute: ProjectIdRoute,
  SettingsDodgeMappingsRoute: SettingsDodgeMappingsRoute,
  SettingsDropdownsRoute: SettingsDropdownsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
